# -*- coding: utf-8 -*-
"""genai1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18LAOyL8-_CKBUT-CdQ76SdfFa7-vWFbC
"""

!pip install transformers
!pip install datasets
!pip install huggingface_hub

from huggingface_hub import notebook_login
notebook_login()

from transformers import pipeline

# Create a text generation pipeline
generator = pipeline('text-generation', model='gpt2')

# Generate text
response = generator(
    "Once upon a time",
    max_length=50,
    num_return_sequences=1,
    pad_token_id=50256,  # Explicitly set pad_token_id to eos_token_id
    truncation=True      # Explicitly enable truncation
)

# Print the generated text
print(response[0]['generated_text'])

from transformers import pipeline

# Create a sentiment analysis pipeline
sentiment_pipeline = pipeline('sentiment-analysis', model='distilbert-base-uncased-finetuned-sst-2-english')
#sentiment_pipeline = pipeline('sentiment-analysis', model='gpt2')
# Analyze sentiment
response = sentiment_pipeline("I  like using the transformers library!")

# Print the sentiment analysis result
print(response[0]['label'])
print(type(response[0]['label']))
print(response[0]['score'])

from transformers import pipeline

# Create a sentiment analysis pipeline
sentiment_pipeline = pipeline('sentiment-analysis', model='distilbert-base-uncased-finetuned-sst-2-english')

# Perform sentiment analysis on some text
texts = [
    "I love this product!",
    "This is the worst experience I've ever had."
]

results = sentiment_pipeline(texts)

for text, result in zip(texts, results):
    print(f"Text: {text}")
    print(f"Sentiment: {result['label']}, Score: {result['score']:.4f}")

from transformers import pipeline


qa_pipeline = pipeline("question-answering", model="distilbert-base-cased-distilled-squad")


questions = [
    "What is the capital of India?",
    "Who invented the telephone?"
]
context = """
India is a country in South Asia. Its capital city is New Delhi.
The telephone was invented by Alexander Graham Bell in the year 1876.
"""

for q in questions:
    result = qa_pipeline(question=q, context=context)
    print(f"Question: {q}")
    print(f"Answer: {result['answer']}, Score: {result['score']:.4f}")
    print("-" * 40)