# -*- coding: utf-8 -*-
"""loaddata

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v3ropw_nIlnUugA_My6Kr6HFdXVoU6QE
"""

import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
path='/content/drive/MyDrive/Classroom/loan_approved.csv'

df=pd.read_csv(path)
df.head(10)

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

le=LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
df.head()

df.head(20)

df['Married']=le.fit_transform(df['Married'])
df.head()

df['Education']=le.fit_transform(df['Education'])
df.head()

df['Self_Employed']=le.fit_transform(df['Self_Employed'])
df.head()

df['Property_Area']=le.fit_transform(df['Property_Area'])
df.head()

df.isnull().sum()

df['LoanAmount'].median()

df['LoanAmount'] = df['LoanAmount'].fillna(df['LoanAmount'].median())

df.isnull().sum()

df.head(20
        )

df['Loan_Amount_Term'].unique()

df['Loan_Amount_Term']=df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].median())

df['Loan_Amount_Term'].unique()

#loan amt term is discreate

df['Loan_Amount_Term'].unique()

df['Loan_Amount_Term'].unique().sort()

df['Loan_Amount_Term'].unique()

df['Loan_Amount_Term'].median()

