# -*- coding: utf-8 -*-
"""loan.csv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AGmKc2mIIUy7Oh3dL8-TtSE24AupRmfV
"""

import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
path='/content/drive/MyDrive/Classroom/loan_approved.csv'

df=pd.read_csv(path)
df.head(10)

df['Loan_Amount_Term'].unique()

df['Loan_Amount_Term'].mode()

df['Loan_Amount_Term']=df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].mode())

df['Loan_Amount_Term'].unique()

from sklearn.preprocessing import LabelEncoder,OneHotEncoder

le=LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
df.head(10)

df['Married']=le.fit_transform(df['Married'])
df.head(10)

df['Education']=le.fit_transform(df['Education'])
df.head(10)

df['Self_Employed']=le.fit_transform(df['Self_Employed'])
df.head(10)

df['Property_Area']=le.fit_transform(df['Property_Area'])
df.head(10)

df.isnull().sum()

df=df.dropna(axis=0)

df.isnull().sum()

df.head(15)

df['Loan_Status (Approved)']=le.fit_transform(df['Loan_Status (Approved)'])
df.head(10)

df.tail(20)

df = df.drop(columns=['Loan_ID'])

df.head(15)

df.tail(20)

df.head(100)

import matplotlib.pyplot as plt
plt.bar(df['ApplicantIncome'],df['Gender'])

df['Education'].unique()

df['Gender'].unique()

mean=df['ApplicantIncome'].mean()
mean

stad=df['ApplicantIncome'].std()
stad

df['ApplicantIncome']=(df['ApplicantIncome']-mean)/stad

df.head(20)

df[(df['ApplicantIncome']>3) | (df['ApplicantIncome']<-3)]

df['CoapplicantIncome'].kurtosis()

from sklearn.preprocessing import PowerTransformer
trans=PowerTransformer(method='yeo-johnson')
df['CoapplicantIncome'] = trans.fit_transform(df[['CoapplicantIncome']])